name: Test and lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[test]"
    - name: Test with pytest
      run: |
        pytest
    - name: Test wordall command exists
      run: |
        command -v wordall
    - name: Test wordall command runs
      run: |
        set +e
        timeout 1 wordall
        exit_code=$?
        # Exit code will be 124 if timed out - i.e. didn't fail or exit prematurely
        if [ "${exit_code}" -ne 124 ]; then
          echo "Received unexpected exit code ${exit_code} from timeout"
          exit 1
        fi


  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
